
#ifndef PORTABLE_WORDSIZES
#ifdef __MW_TARGET_USE_HARDWARE_RESOURCES_H__
#ifndef __MW_TARGET_HARDWARE_RESOURCES_H__
#define __MW_TARGET_HARDWARE_RESOURCES_H__

#define MW_MULTI_TASKING_MODE 1
#include "mw_stm32_board_header.h"
#include "SysTickScheduler.h"
#include "arm_cortex_m_multitasking.h"

#define MW_USECODERTARGET 1
#define MW_TARGETHARDWARE STM32F4xx Based
#define MW_EXTMODEPROTOCOLINFO_CAN_HOSTINTERFACE Simulink
#define MW_EXTMODEPROTOCOLINFO_CAN_LOGGINGBUFFERAUTO 1
#define MW_EXTMODEPROTOCOLINFO_CAN_LOGGINGBUFFERSIZE 1000
#define MW_EXTMODEPROTOCOLINFO_CAN_LOGGINGBUFFERNUM 3
#define MW_EXTMODEPROTOCOLINFO_CAN_MAXCONTIGSAMPLES 10
#define MW_CONNECTIONINFO_SERIAL_BAUDRATE stm32cube.codegen.getConnectivityBaudrate(hCS)
#define MW_CONNECTIONINFO_SERIAL_COMPORT stm32cube.codegen.getConnectivityCOMPort(hCS)
#define MW_CONNECTIONINFO_SERIAL_VERBOSE 1
#define MW_CONNECTIONINFO_TCPIP_IPADDRESS stm32cube.parameters.EthernetConfigIPAddressExternalMode
#define MW_CONNECTIONINFO_TCPIP_PORT 17725
#define MW_CONNECTIONINFO_TCPIP_VERBOSE 1
#define MW_CONNECTIONINFO_CAN_CANVENDOR matlab:stm32cube.codegen.getXCPonCANConnectivity(hCS,'Vendor')
#define MW_CONNECTIONINFO_CAN_CANDEVICE matlab:stm32cube.codegen.getXCPonCANConnectivity(hCS,'Device')
#define MW_CONNECTIONINFO_CAN_CANCHANNEL stm32cube.codegen.getXCPonCANConnectivity(hCS,'Channel')
#define MW_CONNECTIONINFO_CAN_BUSSPEED stm32cube.codegen.getXCPonCANConnectivity(hCS,'Baudrate')
#define MW_CONNECTIONINFO_CAN_CANIDCOMMAND stm32cube.codegen.getXCPonCANConnectivity(hCS,'CANIDCommand')
#define MW_CONNECTIONINFO_CAN_CANIDRESPONSE stm32cube.codegen.getXCPonCANConnectivity(hCS,'CANIDResponse')
#define MW_CONNECTIONINFO_CAN_ISCANIDEXTENDED stm32cube.codegen.getXCPonCANConnectivity(hCS,'IsCANIDExtended')
#define MW_CONNECTIONINFO_CAN_VERBOSE 1
#define MW_EXTMODE_CONFIGURATION Serial
#define MW_EXTMODE_SIGNALBUFFERSIZE 2048.000000
#define MW_EXTMODE_USEREALTIMESTAMPLOGGING 1
#define MW_RTOS Baremetal
#define MW_RTOSBASERATETASKPRIORITY 40
#define MW_SCHEDULER_INTERRUPT_SOURCE 0
#define MW_RUNTIME_BUILDACTION 1
#define MW_RUNTIME_RUNTIMELIBRARY 0
#define MW_RUNTIME_DISABLEPARALLELBUILD 0
#define MW_STM32CUBEMX_PROJECTFILEBUTTON
#define MW_STM32CUBEMX_CREATEPROJECTFILEBUTTON
#define MW_STM32CUBEMX_LAUNCHPROJECTFILEBUTTON
#define MW_STM32CUBEMX_PROJECTFILE C:/Users/power/Documents/AssignmentMOONRIDER/AssignmentMOONRIDER.ioc
#define MW_STM32CUBEMX_DEVICEID STM32F407V(E-G)Tx
#define MW_STM32CUBEMX_FAMILY STM32F4
#define MW_STM32CUBEMX_CONNECTIVITYMODE 0
#define MW_STM32CUBEMX_CONNECTIONPORT 0
#define MW_STM32CUBEMX_MODE 0
#define MW_STM32CUBEMX_ACCESSPORT 0
#define MW_STM32CUBEMX_RESETMODE 0
#define MW_STM32CUBEMX_AUTODETECTBOARD 1
#define MW_STM32CUBEMX_DEVICELIST -1
#define MW_STM32CUBEMX_DEVICELISTREFRESH
#define MW_CLOCKING_CPUCLOCKRATEMHZ 168.000000
#define MW_CONNECTION_SERIALCONFIGUREMODULE 48
#define MW_CONNECTION_SERIALMODULE 1
#define MW_CONNECTION_SERIALPORT COM1
#define MW_CONNECTION_ETHERNETCONFIGUREMODULE 48
#define MW_CONNECTION_ETHERNETPORT 17725.000000
#define MW_CONNECTION_CANCONFIGUREMODULE 48
#define MW_CONNECTION_CANMODULE 0
#define MW_CONNECTION_BAUDRATE 1000000
#define MW_CONNECTION_CANREADSOURCE 0
#define MW_CONNECTION_CANVENDOR -1
#define MW_CONNECTION_CANDEVICE -1
#define MW_CONNECTION_CANCHANNEL -1
#define MW_CONNECTION_ISCANIDEXTENDED 48
#define MW_CONNECTION_CANIDCOMMAND 2
#define MW_CONNECTION_CANIDRESPONSE 3
#define MW_CONNECTIVITY_REFRESH
#define MW_SIMULINKIO_MODELTRANSPORTDATAFCN stm32cube.connectedIO.getConfigSetInfo
#define MW_SIMULINKIO_SERVERDEPLOYFCN stm32cube.connectedIO.updateServer
#define MW_SIMULINKIO_VALIDATESERVERFCN stm32cube.connectedIO.validateIoServer
#define MW_SIMULINKIO_INTERFACE 0
#define MW_SIMULINKIO_VALIDATEBEFORECONNECTFCN stm32cube.connectedIO.connectedIOModelValidation
#define MW_USART_USART1CONFIGUREMODULE 48
#endif
#endif
#endif
